version: 2

project_name: bamboo-base-cli

builds:
  - id: bamboo-base-cli
    main: .
    binary: bamboo-base-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64

archives:
  - id: binaries
    ids:
      - bamboo-base-cli
    format: binary
    name_template: >-
      bamboo-base-cli-{{ .Os }}-{{ .Arch }}{{ if eq .Os "windows" }}.exe{{ end }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

source:
  enabled: false

release:
  mode: keep-existing
  extra_files:
    - glob: scripts/install.sh
    - glob: scripts/install.ps1
    - glob: scripts/uninstall.sh
    - glob: scripts/uninstall.ps1

changelog:
  disable: true
